# Base configs
#baseurl: "https://photography.rampatra.com"
baseurl: "https://zshek001.github.io/photography" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "青音: Photos"
subtitle: "The condensed-state memories"
author: "青音"
header:
 title: "青音: Photos"
 subtitle: "The condensed-state memories"
footer:
 name: "青音"
 bio: "INTP | 00' | 写真 · 被写体 | Hong Kong"
 github: "<a href=\"https://github.com/ramswaroop/photography\"> website framework </a> ;)"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/mmmmmmei2718"
